apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
spec:
  type: NodePort  # Change to LoadBalancer if using cloud
  selector:
    app: ml-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
